# taken from: https://github.com/docker/awesome-compose/tree/master/wordpress-mysql
# admin url: http://localhost/wp-admin
services:
  redis:
    image: redis:6
    volumes:
     - redis_data:/data
    ports:
      - 6379:6379 
    restart: always
    command: " --save 60 1 "      
    environment:
      - somevar=somevalue
volumes:
  redis_data:

  
    